ecm2434_coursework/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views as user
from .views import redirect_home
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join_group/<str:group_name>', user.join_group, name='join_group'),

    path('', redirect_home),
    path("accounts/", include("users.urls"), name='users'),
    path("foodle/", include("foodle.urls"), name='foodle'),
    path("recipes/", include("recipes.urls"), name='recipes')
]

foodle/urls.py
"""
Author: Jamie Elder

Define how all links starting with /foodle/ are handled
"""

from django.urls import path

from . import views

app_name = "foodle"
urlpatterns = [
    path("welcome/", views.welcome, name="welcome"),
    path("home/", views.home, name="home"),
    path("play/", views.play, name="play"),
    path("group-cooks/", views.events, name="events"),
    path("group-cooks/create", views.create_event, name="create_event"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("createGroup", views.createGroup, name="createGroup"),
    path("generateQrCode", views.generateQrCode, name="generateQrCode"),
    path("no_group/", views.no_group, name="no_group"),
]

recipes/urls.py
"""
Author: Jamie Elder
Defines how to render all pages starting with /recipes/
"""

from django.urls import path

from . import views

app_name = "recipes"
urlpatterns = [
    path("create", views.create_recipe, name="create_recipe"),
    path("<int:recipe_id>", views.view_recipe, name="view_recipe"),
    path("", views.view_all_recipes, name="view_all_recipes"),
]

users/urls.py
"""
Author: Jamie Elder

Define how all links starting with /accounts/ are handled
"""

from django.urls import path

from . import views
from django.contrib.auth import views as auth

urlpatterns = [
    path('register/', views.register, name='register'),
    path("terms/", views.terms, name = 'terms'),
    path('login/', auth.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth.LogoutView.as_view(template_name='users/logout.html', next_page=None), name='logout'),
    path('delete_account/', views.delete_user, name='delete_user'),
    path("password_reset/", auth.PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_html_email.html'), name="password_reset"),
    path("password_reset_done/", auth.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password_reset_complete/", auth.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
]

recipes/models.py
"""
Author: Jamie Elder
"""

from django.db import models
from django.contrib.auth.models import User 

class IngredientRating(models.Model):
    """
    Define the database structure for the database of ingredients database
    """
    ingredient_id = models.AutoField(primary_key=True)
    ingredient = models.CharField(max_length=255, unique=True)
    rating = models.IntegerField()
    allergen = models.CharField(max_length=20, null=True, default = None, blank=True)

class Recipe(models.Model):
    """
    Define the database structure for the database of recipes database
    """
    recipe_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    recipe_title = models.CharField(max_length=200)
    recipe_ingredients = models.TextField()
    preparation = models.TextField()
    prep_time = models.PositiveIntegerField(default=0)
    serves_num = models.PositiveIntegerField(default=1)
    sulphates_per_portion = models.PositiveIntegerField(default=0)
    allergens = models.CharField(max_length=50, null=True, default = None, blank=True)
    
    def __str__(self):
        return self.recipe_title

recipes/forms.py
"""
Author: Jamie Elder
"""

from django import forms
from .fields import CommaSeparatedStrings


class RecipeForm(forms.Form):
    """
    Defines information to be collected from  a user when creating a recipe. User, allergens,
    and sulphate score are calculated in backend.
    """

    recipe_title = forms.CharField(max_length=200)
    ingredients = CommaSeparatedStrings(widget=forms.HiddenInput())
    quantities = CommaSeparatedStrings(widget=forms.HiddenInput())
    preparation = forms.CharField()
    prep_time = forms.IntegerField(min_value=0, label="Prep Time (hrs)")
    serves_num = forms.IntegerField(min_value=0, label="Serves")

recipes/views.py
"""
Author: Jamie Elder, Victor Smith
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.generic import CreateView
from .models import Recipe, IngredientRating
from .forms import RecipeForm


@login_required
def view_recipe(request, recipe_id):
    """
    Author: Jamie Elder, Victor Smith
    Render page for viewing specific recipe in detail
    """
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, "recipes/recipe_details.html", {"recipe": recipe})


@login_required
def view_all_recipes(request):
    """
    Author: Jamie Elder, Victor Smith
    Render page for viewing all recipes
    """
    recipes = Recipe.objects.all()
    return render(request, "recipes/all_recipes.html", {"recipes": recipes})


def create_recipe(request):
    """
    Author: Jamie Elder, Victor Smith
    Renders the create recipe page, and defines how to process completed create recipe forms.
    """

    ingredient_ratings = IngredientRating.objects.all()
    form = RecipeForm(request.POST or None)
    context = {"form": form, "ingredient_ratings": ingredient_ratings}
    if request.method == "POST":
        if form.is_valid():
            # Get raw data from form
            ingredients = form.cleaned_data.get("ingredients")
            quantities = [
                int(quantity) for quantity in form.cleaned_data.get("quantities")
            ]
            serves = form.cleaned_data.get("serves_num")

            sulphates_score = get_score(ingredients, quantities, serves)

            # from raw ingredients and quantities create comma separated string list of form "<ingredient> - <quantity)g"
            formatted_ingredients = get_ingredients(ingredients, quantities)

            # from raw ingredients create comma separated string list of allergens by searching ingredients database
            formatted_allergens = get_allergens(ingredients)

            # create new recipe entry in database
            new_recipe = Recipe(
                user=request.user,
                recipe_title=form.cleaned_data.get("recipe_title"),
                recipe_ingredients=formatted_ingredients,
                preparation=form.cleaned_data.get("preparation"),
                prep_time=form.cleaned_data.get("prep_time"),
                serves_num=serves,
                sulphates_per_portion=sulphates_score,
                allergens=formatted_allergens,
            )
            new_recipe.save()
            return redirect("recipes:view_all_recipes")
        return render(request, "recipes/create_recipe.html", context)
    else:
        return render(request, "recipes/create_recipe.html", context)


def get_score(ingredients, quantities, serves):
    """
    Author: Jamie Elder
    Calculates the sulphates per portion of a recipe based on the ingredient sulphate score, quantity,
    and number being cooked for.

    # parameter
    ingredients (str[]): A list of the ingredients in the recipe
    quantities (int[]): A list of the quantities of each ingredient in the recipe
    serves (int): The number of people the recipe serves

    # returns
    The amount of emitted sulphates per portion of food
    """
    score = 0
    for i in range(len(ingredients)):
        try:
            ingredient_rating = IngredientRating.objects.get(ingredient=ingredients[i])
            score += ingredient_rating.rating / 1000 * quantities[i] / serves
        except IngredientRating.DoesNotExist:
            continue
    return score


def get_allergens(ingredients):
    """
    Author: Jamie Elder
    Returns the allergens in a list of ingredients, as a comma separated string

    # parameter
    ingredients (str[]): A list of the ingredients in the recipe

    # returns
    The allergens in ingredients as a comma separated string
    """
    formatted_allergens = ""
    for i in range(len(ingredients)):
        if (
            len(IngredientRating.objects.filter(ingredient=ingredients[i])) > 0
            and IngredientRating.objects.get(ingredient=ingredients[i]).allergen != None
        ):
            if formatted_allergens != "":
                formatted_allergens += ", "

            formatted_allergens += IngredientRating.objects.get(
                ingredient=ingredients[i]
            ).allergen
    return formatted_allergens


def get_ingredients(ingredients, quantities):
    """
    Author: Jamie Elder
    Returns a formatted ingredients string with quantities. The string is of the comma separated value type,
    where each value is of the form "<ingredient> - <quantity)g"

    # parameter
    ingredients (str[]): A list of the ingredients in the recipe
    quantities (int[]): A list of the quantities of each ingredient in the recipe

    # returns
    The formatted string of ingredients and quantities
    """
    formatted_ingredients = ""
    for i in range(len(ingredients)):
        formatted_ingredients += ingredients[i] + " - " + str(quantities[i]) + "g"
        if i < len(ingredients) - 1:
            formatted_ingredients += ", "

    return formatted_ingredients

recipes/templates/recipes/all_recipes.html
<!-- Author: Victor Smith, Jamie Elder -->
<!-- Styling: Victor Smith -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <title>Foodle | View Recipes</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        h1 {
            width: 80%; 
            margin-left: auto; 
            margin-right: auto; 
            text-align: center; 
            opacity: 1; 
            background-color: #ffffff; 
            border-radius: 10px;
        }
         
        table {
            width: 80%;
            margin-left: auto;
            margin-right: auto;
            border-collapse: collapse;
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav a {
            text-decoration: none;
            color: #ffffff;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #949292;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div>
                <a href="{% url 'foodle:home' %}">Back</a>
            </div>
        </div>
    </nav>
    <h1>All Recipes</h1>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Prep (mins)</th>
                <th>Serves</th>
                <th>Allergens</th>
                <th>User</th>
                <th>Env. Score</th>
            </tr>
        </thead>
        <tbody>
            {% for recipe in recipes %}
            <tr>
                <td><a href="{% url 'recipes:view_recipe' recipe_id=recipe.pk %}">{{ recipe.recipe_title }}</a></td>
                <td style="text-align: center;">{{ recipe.prep_time }}</td>
                <td style="text-align: center;">{{ recipe.serves_num }}</td>
                <!-- Display allergens or leave column empty -->
                <td>{% if recipe.allergens == None %}

                    {% else %}
                    {{ recipe.allergens }}
                    {% endif %}
                </td>
                <!-- Display user or replace with "User Deleted" if user does not exist -->
                <td>
                    {% if recipe.user == None %}
                    User Deleted
                    {% else %}
                    {{ recipe.user.username }}
                    {% endif %}
                </td>
                <td style="text-align: center;">{{ recipe.sulphates_per_portion }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

recipes/templates/recipes/base.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Django People</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 0;
        }

        nav div {
            max-width: 800px;
            margin: 0 auto;
            text-align: left;
        }

        a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }

        hr {
            margin-top: 0;
            border: 1px solid #ddd;
        }

        .row {
            justify-content: center;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10">
                <nav>
                    <div>
                        <div style="text-align: left;">
                            <a href="{% url 'foodle:home' %}">Back</a>
                        </div>
                    </div>
                </nav>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>

</html>

recipes/templates/recipes/create_recipe.html
<!-- Author: Victor Smith, Jamie Elder -->
<!-- Styling: Victor Smith -->
{% extends 'recipes/base.html' %}

{% block content %}
{% load static %}

<head>
    <title>Foodle | Create Recipe</title>
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #ffffff;
            padding: 20px;
            opacity: 0.95;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-select,
        .form-control {
            width: 100%;
            padding: 8px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }

        #button-add {
            border: 1px solid #28a745;
            color: #28a745;
            padding: 10px;
            cursor: pointer;
        }

        #button-add:hover {
            background-color: #28a745;
            color: #fff;
        }

        .btn-success {
            background-color: #28a745;
            color: #fff;
        }

        .btn-success:hover {
            background-color: #218838;
        }

        hr {
            margin-top: 0;
            border: 1px solid #ddd;
        }
    </style>
</head>

<div class="container">
    <form method="POST" novalidate>
        {% csrf_token %}
        <!-- Create hidden form inputs for ingredients and quantities -->
        {{ form.ingredients }}
        {{ form.quantities }}
        <div class="form-group">
            {{ form.recipe_title.label }} {{ form.recipe_title }}
        </div>
        <br>
        <div class="form-group">
            {{ form.prep_time.label }} {{ form.prep_time }}
        </div>
        <br>
        <div class="form-group">
            {{ form.serves_num.label }} {{ form.serves_num }}
        </div>
        <br>
        <div class="form-row">
            <div class="form-group col-md-3">
                <select class="form-select" id="Ingredient-Selector">
                    <option selected>Other</option>

                    <!-- add all ingredients in  database to a dropdown -->
                    {% if ingredient_ratings %}
                    {% for rating in ingredient_ratings %}
                    <option value="{{ rating.ingredient }}">{{ rating.ingredient }}</option>
                    {% endfor %}
                    {% endif %}
                </select>
            </div>
            <!-- input for ingredients not in database -->
            <div class="form-group col-md-3">
                <input id="Other-Ingredient-Input" type="text" class="form-control" placeholder="Other Ingredient"
                    aria-label="Other Ingredient">
            </div>
            <div class="form-group col-md-3">
                <input id="Ingredient_Amount" type="text" class="form-control" placeholder="Quantity (g)"
                    aria-label="Quantity (g)">
            </div>
            <!-- Button for moving user inputted ingredients to hidden ingredient/quantity inputs -->
            <div class="form-group col-md-3">
                <div id="button-add" class="btn btn-outline-success"
                    style="margin-left: 50%; transform: translateX(-50%); width: 80%;">Add Ingredient</div>
            </div>
        </div>
        <br>
        <div class="form-group">
            {{ form.preparation.label }} {{ form.preparation }}
        </div>
        <br>

        <div id="Ingredient-container">
        </div>

        <button type="submit" class="btn btn-success"
            style="margin-left: 50%; transform: translateX(-50%); width: 80%;">Upload Recipe</button>
    </form>
</div>

<script type="text/javascript">
    window.onload = function () {
        document.getElementById("button-add").addEventListener("click", add_ingredient);
    }

    function add_ingredient() {
        const IngredientSelector = document.getElementById("Ingredient-Selector");
        const IngredientAmount = document.getElementById("Ingredient_Amount");

        // check quantity is a positive integer
        if (!checkString(IngredientAmount.value)) {
            return;
        } else {
            const newIngredient = document.createElement("div");

            // if user has selected other as the dropdown option, use their text input as the ingredient
            if (IngredientSelector.options[IngredientSelector.selectedIndex].innerHTML == "Other") {
                if (!document.getElementById("Other-Ingredient-Input").value) {
                    return;
                }
                newIngredient.innerText = document.getElementById("Other-Ingredient-Input").value + ' ' + "(" + IngredientAmount.value + "g)";

                if (document.getElementById('id_ingredients').value != '') {
                    document.getElementById('id_ingredients').value += ',';
                }
                // add other ingredient to hidden input
                document.getElementById('id_ingredients').value += document.getElementById("Other-Ingredient-Input").value;

            } else { // else use ingredient user has selected from ingredient dropdown menu
                newIngredient.innerText = IngredientSelector.options[IngredientSelector.selectedIndex].innerHTML + ' ' + "(" + IngredientAmount.value + "g)";

                if (document.getElementById('id_ingredients').value != '') {
                    document.getElementById('id_ingredients').value += ',';
                }
                document.getElementById('id_ingredients').value += IngredientSelector.options[IngredientSelector.selectedIndex].innerHTML;
            }

            if (document.getElementById('id_quantities').value != '') {
                document.getElementById('id_quantities').value += ',';
            }
            // add ingredient to hidden form input
            document.getElementById('id_quantities').value += IngredientAmount.value;

            // add other ingredient to user list of all added ingredients
            document.getElementById("Ingredient-container").appendChild(newIngredient);
        }
    }

    function checkString(string) {
        /**
         * Checks a strings is numerical only
         * 
         * @param string: The string to be tested
         * @return True if string is numerical only, false otherwise
         * */
        return /^[0-9]*$/.test(string);
    }
</script>
{% endblock %}

recipes/templates/recipes/recipe_details.html
<!-- Author: Jamie Elder, Victor Smith -->
<!-- Styling: Victor Smith -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <title>Foodle | View Recipe</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            position: fixed;
            top: 0%;
            left: 0%;
            width: 100%;
        }

        nav a {
            text-decoration: none;
            color: #ffffff;
        }

        h1,p {
            margin: 10px;
            padding: 10px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div>
                <a href="{% url 'recipes:view_all_recipes' %}">Back</a>
            </div>
        </div>
    </nav>

    <h1 style="margin-top: 50px;">{{ recipe.recipe_title }}</h1>
    <p>Preparation: {{ recipe.preparation|linebreaksbr }}</p>
    <p>Prep Time: {{ recipe.prep_time }}</p>
    <p>Serves: {{ recipe.serves_num }}</p>
    <p>User:
        <!-- Display "User Deleted" if user no linger exists -->
        {% if recipe.user == None %}
        User Deleted
        {% else %}
        {{ recipe.user.username }}
        {% endif %}</p>
    <p>Ingredients: {{ recipe.recipe_ingredients }}</p>
    <p>Allergens: {{ recipe.allergens }}</p>
    <p>Sulphates Per Portion: {{ recipe.sulphates_per_portion }}</p>
</body>

</html>