ecm2434_coursework/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views as user
from .views import redirect_home
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join_group/<str:group_name>', user.join_group, name='join_group'),

    path('', redirect_home),
    path("accounts/", include("users.urls"), name='users'),
    path("foodle/", include("foodle.urls"), name='foodle'),
    path("recipes/", include("recipes.urls"), name='recipes')
]

foodle/urls.py
"""
Author: Jamie Elder

Define how all links starting with /foodle/ are handled
"""

from django.urls import path

from . import views

app_name = "foodle"
urlpatterns = [
    path("welcome/", views.welcome, name="welcome"),
    path("home/", views.home, name="home"),
    path("play/", views.play, name="play"),
    path("group-cooks/", views.events, name="events"),
    path("group-cooks/create", views.create_event, name="create_event"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("createGroup", views.createGroup, name="createGroup"),
    path("generateQrCode", views.generateQrCode, name="generateQrCode"),
    path("no_group/", views.no_group, name="no_group"),
]

recipes/urls.py
"""
Author: Jamie Elder
Defines how to render all pages starting with /recipes/
"""

from django.urls import path

from . import views

app_name = "recipes"
urlpatterns = [
    path("create", views.create_recipe, name="create_recipe"),
    path("<int:recipe_id>", views.view_recipe, name="view_recipe"),
    path("", views.view_all_recipes, name="view_all_recipes"),
]

users/urls.py
"""
Author: Jamie Elder

Define how all links starting with /accounts/ are handled
"""

from django.urls import path

from . import views
from django.contrib.auth import views as auth

urlpatterns = [
    path('register/', views.register, name='register'),
    path("terms/", views.terms, name = 'terms'),
    path('login/', auth.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth.LogoutView.as_view(template_name='users/logout.html', next_page=None), name='logout'),
    path('delete_account/', views.delete_user, name='delete_user'),
    path("password_reset/", auth.PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_html_email.html'), name="password_reset"),
    path("password_reset_done/", auth.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password_reset_complete/", auth.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
]

foodle/models.py
"""
Author: Jamie Elder
"""

from django.db import models
from django.contrib.auth.models import User, Group
from recipes.models import Recipe  

class MealEvent(models.Model):
    """
    Define the database structure for the database of meal events
    """
    
    Meal_Event_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    score = models.PositiveBigIntegerField(default = 0)

foodle/forms.py
"""
Author: Jamie Elder
"""

from django import forms
from datetime import datetime
from recipes.models import Recipe
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.contrib.admin.widgets import AdminDateWidget
from django.utils import timezone


def not_in_past(date_time):
    """
    A custom requirement to check a if a date is in the past. Used to ensure cooking events are not
    created with dates in the past.

    # Parameters
    date_time (datetime): The datetime to be checked

    # Throws
    ValidationError: If date_time is in the past
    """
    if timezone.now() >= date_time:
        raise ValidationError("Your event date cannot be in the past")


class CreateMealEvent(forms.Form):
    """
    A form for creating a new meal event
    """

    # Get a list of all the recipe ids and titles 
    recipe_choices = []
    for recipe in Recipe.objects.all():
        recipe_choices.append((recipe.recipe_id, recipe.recipe_title))

    # Create meal event form fields
    recipe = forms.ChoiceField(choices=recipe_choices)
    date_time = forms.DateTimeField(
        validators=[not_in_past],
        # Use widget for calendar like selection of a date
        widget=forms.widgets.DateTimeInput(attrs={"type": "datetime-local"}),
    )


class createGroupForm(forms.ModelForm):
    """
    Form fro creating a new group. Gets a name input.
    """
    class Meta:
        model = Group
        fields = ["name"]

foodle/views.py
"""
Author: Jamie Elder, Victor Smith
"""

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import user_passes_test

from .models import MealEvent
from recipes.models import Recipe
from users.models import UserProfile
from django.contrib.auth.models import User, Group
from .forms import CreateMealEvent
from .qr import genQrCode
from PIL import Image
import io

from .forms import createGroupForm
from django.contrib.auth.decorators import login_required


def user_in_group(user):
    """
    Author: Jamie Elder
    Check that a user is a member of one and only one group

    # parameters
    user (AbstractUser): The user to be checked

    # returns
    True if the user is a member of exactly one group, False otherwise
    """

    return user.is_authenticated and user.groups.count() == 1


def welcome(request):
    """
    Author: Jamie Elder
    Renders the welcome page
    """
    return render(request, "foodle/welcome.html")


@login_required
def home(request):
    """
    Author: Jamie Elder
    Renders the user home page. Accessible only if logged in.
    """
    return render(request, "foodle/home.html")


@login_required
def play(request):
    """
    Author: Jamie Elder
    Renders the user Foodle game page. Accessible only if logged in. Updates user score with new Foodle ponts.
    """

    # Update the user score when the user caches their points
    if request.method == "POST":
        request.user.userprofile.foodle_score += int(request.POST["score"])
        request.user.userprofile.save()
        return redirect("foodle:home")
    else:
        return render(request, "foodle/foodle.html")


@user_passes_test(user_in_group, login_url="foodle:no_group")
def events(request):
    """
    Author: Jamie Elder
    Renders the view cooking events page. Accessible only if logged in and a member of one group.
    """

    user_group = request.user.groups.first()
    # get all cooking events of the user's group
    cooking_events = MealEvent.objects.filter(group=user_group).order_by("-date_time")
    context = {"cooking_events": cooking_events}
    return render(request, "foodle/events.html", context)


@user_passes_test(user_in_group, login_url="foodle:no_group")
def create_event(request):
    """
    Author: Jamie Elder
    Renders the create cooking event page and handles cooking event creation form submissions.
    Accessible only if logged in and a member of one group.
    """

    if request.method == "POST":
        form = CreateMealEvent(request.POST)
        if form.is_valid():
            event_recipe = Recipe.objects.get(recipe_id=form.cleaned_data.get("recipe"))
            event_group = request.user.groups.first()

            # score = (10 - recipescore/10) * num people
            event_score = max(
                0,
                round(
                    (10 - event_recipe.sulphates_per_portion / 10)
                    * User.objects.filter(groups=event_group).count()
                ),
            )
            new_event = MealEvent(
                user=request.user,
                group=event_group,
                date_time=form.cleaned_data.get("date_time"),
                recipe=event_recipe,
                score=event_score,
            )
            new_event.save()
            return redirect("foodle:events")

    else:
        form = CreateMealEvent()
    return render(request, "foodle/create_event.html", {"form": form})


@login_required
def leaderboard(request):
    """
    Author: Jamie Elder
    Renders the leaderboard page. Accessible only if logged in.
    """
    profiles = list(UserProfile.objects.all())
    profiles.sort(
        reverse=True,
        key=lambda profile: profile.foodle_score
        + profile.env_score,  # combine foodle and recipe scores
    )
    context = {"top_100_profiles": profiles[:100]}
    return render(request, "foodle/leaderboard.html", context)


@user_passes_test(lambda user: user.is_superuser)
def createGroup(request):
    """
    Author: Victor Smith
    Renders the create group page and handle create group form submissions.
    Accessible only to admins.
    """
    all_groups = Group.objects.all()
    if request.method == "POST":
        form = createGroupForm(request.POST or None)
        if form.is_valid():
            form.save()
        return render(request, "foodle/createGroup.html", {"all": all_groups})
    else:
        return render(request, "foodle/createGroup.html", {"all": all_groups})


@user_passes_test(lambda user: user.is_superuser)
def generateQrCode(request):
    """
    Author: Victor Smith
    Renders the generate QR Code page. Accessible only to admins.
    """
    all_groups = Group.objects.all()
    if request.method == "POST":
        newQr = Image.new("RGB", (240, 240), color=(0, 0, 0)) # define QR code image dimensions
        newQr = genQrCode(request.POST["group_name"]) # generate QR link to specific group joining page

        buff = io.BytesIO()
        newQr.save(buff, "jpeg")
        return HttpResponse(buff.getvalue(), content_type="image/jpeg")
    else:
        return render(request, "foodle/generateQrCode.html", {"all": all_groups})


def no_group(request):
    """
    Author: Jamie Elder
    Render redirect page for when user accesses a group only page without a group
    """
    return render(request, "foodle/no_group.html")

foodle/templates/foodle/createGroup.html
<!-- Author: Victor Smith -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Admin page for creating new kitchen groups -->
{% extends 'base.html' %}

{% block content %}
{% load static %}

<head>
    <title>Admin | Create Group</title>
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        table {
            margin-top: 10px;
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #949292;
            font-weight: bold;
        }
    </style>
</head>
<nav style="position: fixed; top: 0%; width: 100%; text-align: center; color: #ffffff;">
    <div>
        <div>
            <a href="{% url 'foodle:generateQrCode' %}">Generate Group Qr Codes</a>
        </div>
    </div>
</nav>
<h1>CREATE GROUP</h1>
<table>
    <tr>
        <th style="text-align: center;">Group Name</th>

    </tr>
    {% for item in all %}
    <tr>
        <th>{{ item.name}}</th>
    </tr>
    {% endfor %}

    <hr>

    <form method="POST" action="{% url 'foodle:createGroup' %}">
        {% csrf_token %}
        <div class="mb-3">
            <div>
                <input type="name" class="name" name="name" aria-describedby="name" placeholder="New Group Name"
                    style="width: 100%;">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Create new Group</button>
</form>
<hr>
{% endblock %}

foodle/templates/foodle/create_event.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Page for creating cooking events by selecting a recipe and date -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <title>Foodle | Create Event</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav a {
            text-decoration: none;
            color: #3498db;
            margin-right: 10px;
        }

        nav a:hover {
            color: #2980b9;
        }

        form {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 80%;
        }

        p {
            margin-bottom: 15px;
        }

        button {
            background-color: #3498db;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #2980b9;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div>
                <a href="{% url 'foodle:events' %}" style="color: #ffffff;">Back</a>
                <a href="{% url 'foodle:home' %}" style="color: #ffffff;">Home</a>
            </div>
        </div>
    </nav>

    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p style="text-align: center; width: 100%;">{{ field.label }}: <br> {{ field }}</p>
        {% endfor %}
        <button type="submit" style="width: 100%;">Create Event</button>
    </form>
</body>

</html>

foodle/templates/foodle/events.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Page for viewing group cooking events -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foodle | Cooking Events</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        table {
            width: 90%;
            margin-left: auto;
            margin-right: auto;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ffffff;
            opacity: 1;
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #149a57;
            color: #fff;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
            opacity: 0.95;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #949292;
            opacity: 0.95;
            font-weight: bold;
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav a {
            text-decoration: none;
            color: #3498db;
            margin-right: 10px;
        }

        nav a:hover {
            color: #2980b9;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div>
                <a href="{% url 'foodle:home' %}" style="color: #ffffff;">Back</a>
                <a href="{% url 'foodle:create_event' %}" style="color: #ffffff;">Create an Event</a>
            </div>
        </div>
    </nav>

    {% if cooking_events %}
    <table>
        <tr>
            <th style="text-align: center;">Cook</th>
            <th style="text-align: center;">Recipe</th>
            <th style="text-align: center;">Date</th>
            <th style="text-align: center;">Env. Score</th>
        </tr>
        {% for event in cooking_events %}
        <tr>
            <td>{{event.user.username}}</td>
            <td><a href="{% url 'recipes:view_recipe' event.recipe.recipe_id %}">{{event.recipe.recipe_title}}</a></td>
            <td>{{event.date_time}}</td>
            <td style="text-align: center;">{{event.score}}</td>
        </tr>
        {% endfor %}
    </table>

    <!-- if cooking events is false then group has no cooking events -->
    {% else %}
    <p>Your group currently has no cooking events</p>
    {% endif %}
</body>

</html>

foodle/templates/foodle/foodle.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith -->
<!-- The Foodle game page with points display and a button for caching points -->
{% extends 'foodle/index.html' %}
{% block content %}
<html>

<head>
  <title>Foodle | Play Foodle</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale = 1.0" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'foodle/css/foodle.css' %}" />
  <script src="{% static 'foodle/js/foodle.js' %}"></script>
</head>

<body>
  <h1 id="title">Foodle</h1>
  <hr />
  <br />
  <div id="board"></div>
  <p id="points">Points: 0</p>
  <button id="submit_score">Submit and Return</button>
  <!-- header for displaying the foodle answers - initially hidden with a filler to maintain height of element -->
  <h1 id="answer" style="visibility: hidden;"> FILLER </h1>

  <form id="score_form" style="display: none;" action="" method="POST">
    {% csrf_token %}
    <input type="hidden" id="score_field" step="0" required name="score">
  </form>
</body>

</html>
{% endblock content %}

foodle/templates/foodle/generateQrCode.html
<!-- Author: Victor Smith -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Admin page for generating QR codes for joining a grup -->

{% extends 'base.html' %}

{% block content %}
{% load static %}

<head>
    <title>Admin | Generate QR Codes</title>
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        h1 {
            width: 80%;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            opacity: 1;
            background-color: #ffffff;
            border-radius: 10px;
        }

        button {
            width: 80%;
            margin-left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            position: fixed;
            top: 0%;
            left: 0%;
            width: 100%;
        }

        nav a {
            text-decoration: none;
            color: #ffffff;
            margin-right: 10px;
        }

        table {
            margin-top: 10px;
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 90%;
            margin-left: 50%;
            -ms-transform: translate(-50%, 0%);
            transform: translate(-50%, 0%);
            margin-bottom: 20px;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(odd) {
            background-color: #ffffff;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #949292;
            font-weight: bold;
        }
    </style>
</head>
<nav>
    <div>
        <div>
            <a href="{% url 'foodle:createGroup' %}">Create Group</a>
        </div>
    </div>
</nav>
<h1>ALL GROUPS</h1>
<hr>
<table>
    <tr>
        <th style="text-align: center;">Group Name</th>
        <th style="text-align: center;">Create Qr code</th>
    </tr>
    {% for item in all %}
    <tr>
        <th style="text-align: center;">{{ item.name }}</th>
        <th>
            <form method="POST" action="{% url 'foodle:generateQrCode' %}">
                {% csrf_token %}
                <input name="group_name" value="{{ item.name }}" style="width: 0px; visibility: hidden;">

                <button type="submit" class="btn btn-primary">QR code</button>
            </form>
        </th>
    </tr>
    {% endfor %}

    {% endblock %}

foodle/templates/foodle/home.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Home page with welcome message and links to the rest of the Foodle app -->

{% extends 'foodle/index.html' %}

{% block content %}
{% load static %}

<head>
    <title>Foodle | Home</title>
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        .alert {
            background-color: #4caf50;
            color: #fff;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h3 {
            margin: 0;
            color: #333;
        }

        form {
            margin-top: 20px;
            position: fixed; 
            top: 82%; 
            width: 100%;
        }

        button {
            width: 90%; 
            margin-left: 50%; 
            -ms-transform: translate(-50%, -50%); 
            transform: translate(-50%, -50%);
            padding: 5px;
            border-radius: 5px;
            background-color: #28a745;
        }

        button:hover {
            background-color: #2980b9;
        }
    </style>
</head>

<!-- Display welcome message, username, and combined points -->
<div class="alert" role="alert">
    <h3>Welcome to Foodle {{ user.username }}!</h3>
    <h3>Your current score is {{ user.userprofile.foodle_score|add:user.userprofile.env_score}}!</h3>
</div>

    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    <form method="get" action="{% url 'delete_user' %}" style="top: 90%;">
        {% csrf_token %}
        <button type="submit" style="background-color: #ff0000;">Delete Account</button>
    </form>
{% endblock content %}

foodle/templates/foodle/index.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        nav {
            background-color: #3498db;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav a {
            text-decoration: none;
            color: #fff;
            margin-right: 10px;
        }

        nav a:hover {
            color: #ecf0f1;
        }

        div {
            margin: 20px;
        }

        div a {
            text-decoration: none;
            color: black;
            display: block;
            margin-bottom: 10px;
        }

        div a:hover {
            color: #2980b9;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div style="text-align: left;">
                <a href="{% url 'foodle:home' %}">Home</a>
                <a href="{% url 'foodle:play' %}">Play Foodle</a>
                <a href="{% url 'foodle:events' %}">Cooking Events</a>
                <a href="{% url 'recipes:create_recipe' %}">Make Recipes</a>
                <a href="{% url 'recipes:view_all_recipes' %}">View Recipes</a>
                <a href="{% url 'foodle:leaderboard' %}">Leaderboard</a>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
</body>

</html>

foodle/templates/foodle/leaderboard.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Leaderboard displaying top 100 users by combined score -->

{% extends 'foodle/index.html' %}

{% block content %}

{% load static %}

<head>
    <title>Foodel | Leaderboard</title>
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

    table {
        width: 90%;
        border-collapse: collapse;
        margin-top: 20px;
        margin-left: auto;
        margin-right: auto  ;
    }

        th,
        td {
            border: 1px solid #ffffff;
            opacity: 1;
            padding: 10px;
            text-align: left;
        }

    th {
        background-color: #149a57;
        color: #fff;
        text-align: center;
    }

        tr:nth-child(odd) {
            background-color: #ffffff;
            opacity: 0.95;
            font-weight: bold;
        }

    tr:nth-child(even) {
        background-color: #949292;
        opacity: 0.95;
        font-weight: bold;
    }
    
    td {
        text-align: center;
    }

        p {
            margin-top: 20px;
        }
    </style>
</head>

{% if top_100_profiles %}
<table>
    <tr>
        <th>Username</th>
        <th>Score</th>
    </tr>
    {% for profile in top_100_profiles %}
    <tr>
        <td>{{ profile.user.username }}</td>
        <td>{{ profile.foodle_score|add:profile.env_score }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No users currently available</p>
{% endif %}
{% endblock content %}

foodle/templates/foodle/no_group.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith -->
<!-- Redirect page for users without a group trying to use group only features -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foodle | No Group</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        nav {
            background-color: #28a745;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        nav a {
            text-decoration: none;
            color: #3498db;
            margin-right: 10px;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <div>
                <a href="{% url 'foodle:home' %}" style="color: #ffffff;">Back</a>
            </div>
        </div>
    </nav>
    <div style="background-color: #fff; width: 80%; text-align: center; margin-top: 10%; border-radius: 10px; margin-left: 50%; -ms-transform: translate(-50%, 0%); transform: translate(-50%, 0%); padding: 20px;">
        <h1>You must be part of a group to access this page. Please join a group by scanning the QR code in your accomodation kitchen.</h1>
    </div>
</body>

</html>

foodle/templates/foodle/welcome.html
<!-- Author: Jamie Elder -->
<!-- Styling: Victor Smith, Dylan Carter -->
<!-- Welcome page with links to log in a sign up -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foodle | Welcome</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/login_styles.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        .alert {
            background-color: #c0fcc2;
            opacity: 0.9;
            color: #000000;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin: 20px auto;
            max-width: 400px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h3 {
            margin: 0;
        }

        a {
            text-decoration: none;
            color: #3498db;
            margin-right: 10px;
        }

        a:hover {
            color: #2980b9;
        }
    </style>
</head>

<body>
    <div class="alert" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
</body>

</html>